dist: xenial
language: python
python:
  - "3.6"

install:
  - ./python_env.sh

addons:
  postgresql: "10"

before_script:
  - psql -c 'create database test_db;' -U postgres

  script:
  - pytest webapp/apps/ -v