version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  webbase:
    build:
      context: ./
      dockerfile: Dockerfile.base
    image: webbase
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
      - USE_STRIPE=False
      - DEBUG=True
      - WORKERS=${WORKERS}:5050
      - LOCAL=True
      - BUCKET=cs-outputs-dev-1
    ports:
      - "8000:8000"
    container_name: web
    depends_on:
      - db
      - webbase

volumes:
  postgres_data:
