version: '3'
services:
  pslmodels_taxbrain_sim:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.tasks
      args:
        TITLE: "Tax-Brain"
        OWNER: "PSLmodels"
        SIM_TIME_LIMIT: "500"
        BRANCH: "compconfig"
        REPO_URL: "https://github.com/andersonfrailey/Tax-Brain"
        RAW_REPO_URL: "https://raw.githubusercontent.com/andersonfrailey/Tax-Brain"
        AWS_ACCESS_KEY_ID: 
        AWS_SECRET_ACCESS_KEY: 
    image: "comporg/pslmodels_taxbrain_tasks:${TAG}"
    entrypoint: ./celery_sim.sh PSLmodels Tax-Brain
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
    depends_on:
      - redis
      - celerybase
    env_file:
      - ./dockerfiles/dev.env
    networks:
      - comp-ce_comp-net
  pslmodels_taxbrain_io:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.tasks
      args:
        TITLE: "Tax-Brain"
        OWNER: "PSLmodels"
        SIM_TIME_LIMIT: "500"
        BRANCH: "compconfig"
        REPO_URL: "https://github.com/andersonfrailey/Tax-Brain"
        RAW_REPO_URL: "https://raw.githubusercontent.com/andersonfrailey/Tax-Brain"
        AWS_ACCESS_KEY_ID: 
        AWS_SECRET_ACCESS_KEY: 

    image: "comporg/pslmodels_taxbrain_tasks:${TAG}"
    entrypoint: ./celery_io.sh PSLmodels Tax-Brain
    depends_on:
      - redis
      - celerybase
    env_file:
      - ./dockerfiles/dev.env
    networks:
      - comp-ce_comp-net