apiVersion: v1
kind: Service
metadata:
  name: # [owner]-[title]-dask-scheduler
  labels:
    app: # [owner]-[title]-dask-scheduler
    component: scheduler
spec:
  ports:
    - name: # [owner]-[title]-dask-scheduler
      port: 8786
      targetPort: 8786
    - name: # [owner]-[title]-dask-webui
      port: 8787
      targetPort: 8787
  selector:
    app: # [owner]-[title]-dask-scheduler
    component: scheduler
