apiVersion: apps/v1
kind: Deployment
metadata:
  name: # [owner]-[title]-dask-scheduler
  labels:
    app: # [owner]-[title]-dask-scheduler
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: # [owner]-[title]-dask-scheduler
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: # [owner]-[title]-dask-scheduler
        component: scheduler
    spec:
      containers:
        - name: # [owner]-[title]-dask-scheduler
          image: daskdev/dask:latest
          imagePullPolicy: IfNotPresent
          args:
            - dask-scheduler
            - --port
            - "8786"
            - --bokeh-port
            - "8787"
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
            requests:
              cpu: 0.5
              memory: 2G
            limits:
              cpu: 1.8
              memory: 6G
