apiVersion: v1
kind: Service
metadata:
  name: # [owner]-[title]-dask-submitter
  labels:
    app: # [owner]-[title]-dask-submitter
    component: submitter
spec:
  ports:
    - name: # [owner]-[title]-dask-submitter
      port: 8789
      targetPort: 8789
  selector:
    app: # [owner]-[title]-dask-submitter
    component: submitter
