apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: gcr.io/comp-workers/flask:k8s-2
        imagePullPolicy: Always
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 5050