apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SAFEOWNER}}-{{SAFETITLE}}-{{ACTION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{SAFEOWNER}}-{{SAFETITLE}}-{{ACTION}}
  template:
    metadata:
      labels:
        app: {{SAFEOWNER}}-{{SAFETITLE}}-{{ACTION}}
    spec:
      containers:
      - name: {{SAFEOWNER}}-{{SAFETITLE}}-{{ACTION}}
        image: gcr.io/{{PROJECT}}/{{SAFEOWNER}}_{{SAFETITLE}}_tasks:{{TAG}}
        imagePullPolicy: Always
        command: ["./celery_{{ACTION}}.sh"]
        args: ["{{OWNER}}", "{{TITLE}}"]
        resources:
          requests:
            memory: "{{REQUEST_MEMORY}}"
            cpu: "{{REQUEST_CPU}}"
          limits:
            memory: "{{MAX_MEMORY}}"
            cpu: "{{MAX_CPU}}"
        env:
        - name: OUTPUTS_VERSION
          value: v1
        - name: TITLE
          value: "{{TITLE}}"
        - name: OWNER
          value: "{{OWNER}}"
        - name: AWS_ACCESS_KEY_ID
          value: "{{AWS_ACCESS_KEY_ID}}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "{{AWS_SECRET_ACCESS_KEY}}"
        - name: COMP_URL
          valueFrom:
            secretKeyRef:
              name: worker-secret
              key: COMP_URL
        - name: COMP_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: worker-secret
              key: COMP_API_TOKEN
        - name: BUCKET
          valueFrom:
            secretKeyRef:
              name: worker-secret
              key: BUCKET
