version: '3'
services:
  flask:
    image: "comp/flask:${TAG}"
    ports:
      - 5050:5050
    depends_on:
      - redis
      - taxcalc_tasks
  taxcalc_tasks:
    image: "comp/taxcalc_tasks:${TAG}"
    depends_on:
      - redis
  redis:
    image: redis
