version: '3.7'
services:
  {{SAFEOWNER}}_{{SAFETITLE}}_tasks:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.tasks
      args:
        TITLE: "{{TITLE}}"
        OWNER: "{{OWNER}}"
        SIM_TIME_LIMIT: "{{SIM_TIME_LIMIT}}"
        BRANCH: "{{BRANCH}}"
        REPO_URL: "{{REPO_URL}}"
        RAW_REPO_URL: "{{RAW_REPO_URL}}"
        AWS_ACCESS_KEY_ID: {{AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: {{AWS_SECRET_ACCESS_KEY}}
        BUILD_NUM: {{BUILD_NUM}}
    image: "{{SAFEOWNER}}_{{SAFETITLE}}_tasks:${TAG}"
    depends_on:
      - celerybase
      - redis


  {{SAFEOWNER}}_{{SAFETITLE}}_sim:
    image: "{{SAFEOWNER}}_{{SAFETITLE}}_tasks:${TAG}"
    entrypoint: ./celery_sim.sh {{OWNER}} {{TITLE}}
    environment:
      - AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}
    depends_on:
      - {{SAFEOWNER}}_{{SAFETITLE}}_tasks
    networks:
      worker_net:

  {{SAFEOWNER}}_{{SAFETITLE}}_io:
    image: "{{SAFEOWNER}}_{{SAFETITLE}}_tasks:${TAG}"
    entrypoint: ./celery_io.sh {{OWNER}} {{TITLE}}
    depends_on:
      - {{SAFEOWNER}}_{{SAFETITLE}}_tasks
    networks:
      worker_net: