version: '3'
services:
  flask:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.flask
    image: "comporg/flask:${TAG}"
    ports:
      - 5050:5050
    container_name: flask
    depends_on:
      - redis
      # Add celery workers here:
      # - {project_name}_tasks
      - hdoupe_matchups_sim
      - hdoupe_matchups_io
      - distributed
    networks:
      - comp_comp-net

####################################################
  hdoupe_matchups_sim:
    build:
      context: ./
      dockerfile: dockerfiles/projects/Dockerfile.hdoupe_matchups_tasks
    image: "comporg/hdoupe_matchups_tasks:${TAG}"
    depends_on:
      - redis
      - celerybase
    networks:
      - comp_comp-net
  hdoupe_matchups_io:
    build:
      context: ./
      dockerfile: dockerfiles/projects/Dockerfile.hdoupe_matchups_tasks
    image: "comporg/hdoupe_matchups_tasks:${TAG}"
    entrypoint: celery -A celery_app.hdoupe_matchups_tasks worker --loglevel=info --concurrency=1 -Q hdoupe_matchups_inputs_queue
    depends_on:
      - redis
      - celerybase
    networks:
      - comp_comp-net

####################################################
  celerybase:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.celerybase
    image: "comporg/celerybase"
  distributed:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile
    image: "comporg/distributed"

####################################################
  redis:
    image: redis
    networks:
      - comp_comp-net

####################################################
networks:
  comp_comp-net:
    external: true