apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image:
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 5050
          env:
            - name: COMP_URL
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: COMP_URL
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - small
