- owner: hdoupe
  title: Matchups
  branch: master
  repo_url: https://github.com/hdoupe/Matchups
  cluster_type: single-core
  env:
    BUILD_NUM: 0
  affinity:
    size: small
  secrets:
    some_secret: hello world
  resources:
    limits:
      cpu: 1000m
      memory: 4000Mi
    requests:
      cpu: 500m
      memory: 300Mi
  sim_time_limit: 60
- owner: PSLmodels
  title: OG-USA
  sim_time_limit: 10000
  repo_url: https://github.com/PSLmodels/OG-USA
  branch: master
  cluster_type: dask
  resources:
    requests:
      memory: 18G
      cpu: 3
    limits:
      memory: 22G
      cpu: 4
  env:
    BUILD_NUM: 2
    INSTALL_NUM: 0
